from enum import Enum

class Icons(Enum):
    LOGO = "logo.png"
    ARROW_DOWN = "arrow_down.png"
    ARROW_UP = "arrow_up.png"
    SEARCH = "search.png"
    FILE = "file.png"
    FOLDER = "folder.png"
    SAVE = "save.png"
    SAVE_AS = "save_as.png"
    CROSS = "cross.png"
    SCISSORS = "scissors.png"
    COPY = "copy.png"
    PASTE = "paste.png"
    UNDO = "undo.png"
    REDO = "redo.png"
    BOLD = "bold.png"
    ITALIC = "italic.png"
    UNDERLINE = "underline.png"
    STRIKETHROUGH = "strikethrough.png"
    PICKER = "picker.png"
    FILLING = "filling.png"
    SPACING = "spacing.png"
    INDENTATION = "indentation.png"
    ALIGN_LEFT = "align_left.png"
    ALIGN_CENTER = "align_center.png"
    ALIGN_RIGHT = "align_right.png"
    ALIGN_JUSTIFY = "align_justify.png"
    PICTURE = "picture.png"
    LINK = "link.png"